# Generated by Django 5.0.7 on 2025-08-23 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scout_Company_name', models.CharField(max_length=100)),
                ('scout_gmail', models.EmailField(max_length=254)),
                ('scout_password', models.CharField(max_length=100)),
                ('scout_phone', models.CharField(max_length=15)),
                ('scout_address', models.TextField()),
                ('scout_reg_no', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Seeker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seeker_Full_name', models.CharField(max_length=100)),
                ('seeker_gmail', models.EmailField(max_length=254)),
                ('seeker_password', models.CharField(max_length=100)),
                ('seeker_phone', models.CharField(max_length=15)),
                ('seeker_address', models.TextField()),
                ('seeker_citi_no', models.CharField(max_length=50)),
                ('seeker_dof', models.DateField()),
            ],
        ),
    ]
