# Generated by Django 5.0.7 on 2025-08-31 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BountyHunting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('job_description', models.TextField()),
                ('job_location', models.CharField(max_length=100)),
                ('job_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('job_poasted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BountyHunting.scout')),
            ],
        ),
    ]
