# Generated by Django 5.0.7 on 2026-01-09 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BountyHunting', '0002_jobpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_seeker_img', models.FileField(blank=True, null=True, upload_to='index/seeker/')),
                ('index_scout_img', models.FileField(blank=True, null=True, upload_to='index/scout/')),
                ('ads_img', models.FileField(blank=True, null=True, upload_to='ads/')),
            ],
        ),
        migrations.AddField(
            model_name='jobpost',
            name='job_imges',
            field=models.FileField(blank=True, null=True, upload_to='jobpost/images/'),
        ),
        migrations.CreateModel(
            name='SeekerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seeker_see', models.FileField(blank=True, null=True, upload_to='seeker/see/')),
                ('seeker_highschool', models.FileField(blank=True, null=True, upload_to='seeker/highschool/')),
                ('seeker_bachelor', models.FileField(blank=True, null=True, upload_to='seeker/bachelor/')),
                ('seeker_master', models.FileField(blank=True, null=True, upload_to='seeker/master/')),
                ('seeker_phd', models.FileField(blank=True, null=True, upload_to='seeker/phd/')),
                ('seeker_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BountyHunting.seeker')),
            ],
        ),
    ]
