# Generated by Django 5.0.7 on 2026-01-10 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BountyHunting', '0003_images_jobpost_job_imges_seekerprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ads_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ads_img', models.FileField(blank=True, null=True, upload_to='ads/')),
            ],
        ),
        migrations.CreateModel(
            name='Index_Scout_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_scout_img', models.FileField(blank=True, null=True, upload_to='index/scout/')),
            ],
        ),
        migrations.CreateModel(
            name='Index_Seeker_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_seeker_img', models.FileField(blank=True, null=True, upload_to='index/seeker/')),
            ],
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
