# Generated by Django 5.0.7 on 2026-01-11 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BountyHunting', '0004_ads_images_index_scout_images_index_seeker_images_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_img', models.FileField(blank=True, null=True, upload_to='login/')),
            ],
        ),
        migrations.CreateModel(
            name='Register_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_img', models.FileField(blank=True, null=True, upload_to='register/')),
            ],
        ),
        migrations.AddField(
            model_name='scout',
            name='scout_images',
            field=models.FileField(blank=True, null=True, upload_to='scout/images/'),
        ),
        migrations.AddField(
            model_name='seeker',
            name='seeker_images',
            field=models.FileField(blank=True, null=True, upload_to='seeker/images/'),
        ),
    ]
